### ISSUE TITLE
Transactions don't need flags

### ISSUE THREAD

**Issue by tbm** [glasserc/ledger-to-beancount#11]
You wrote in commit  596e5bf:

> Flags are preserved, but since every transaction has to have a flag,
>  we default to the "*" flag for any unflagged transactions

Actually, that's not true.  But if you don't have a flag, you have to write "txn" in beancount.  This is documented in the beancount syntax guide.

**Comment by glasserc** [comment]
Also in the beancount syntax guide is:

> In the case of the first example using “txn” to leave the transaction unflagged, the default flag (“*”) will be set on the transaction object.

You can see that in action at https://bitbucket.org/blais/beancount/src/38359c3d1c58079c5ee635254ff7cd803ac3b50c/beancount/parser/grammar.y#lines-262:264. Indeed, the definition of `Transaction` in `beancount.core.data` shows `Flag` as mandatory, not optional, and if you take a file such as

```
2010-01-01 open Assets:Cash
2010-01-01 open Expenses:Cash

2011-01-01 txn "Spend money"
  Expenses:Cash   10 USD
  Assets:Cash
```

and run `bean-doctor context` on it, you'll get:

```
2011-01-01 * "Spend money"
  Expenses:Cash   10 USD
  Assets:Cash    -10 USD
```

At present, `beancount` does not have a way to define a `Transaction` without a flag.

**Comment by tbm** [comment]
Oh I didn't realise that. That's a bit unfortunate.

**Comment by tbm** [comment]
I wonder if we should open a beancount issue.  imho `txn` and `*` should have a different meaning.

**Comment by glasserc** [comment]
I don't have a strong opinion on the subject. I've never actually used flags myself, and I'm not really sure what I would use them for, so it's hard for me to know what their true meanings should be. There are plenty of flags available (the grammar accepts all of `!&#?%PSTCURM`), so you could easily redefine "*" to mean "unchecked" and pick some other one to mean "checked". I do agree that in a design that generally pays a lot of attention to semantic correctness, this is a bit strange. I wonder if it was just a shortcut taken while writing the parser so as not to have to consider the case of missing flags.
