### ISSUE TITLE
Currency Formatting

### ISSUE THREAD

**Issue by taprix** [glasserc/ledger-to-beancount#4]
The currency formatting could be improved if it could parse and edit the currency in Beancount format. 
Just as an example : 

```

2017-07-13 * "Drinks with Friends"
  Expenses:Personal:Dave:Beverage:Beer     EUR 13.00
  Assets:Cash

```

To as follows:-

```
2017-07-13 * "Drinks with Friends"
  Expenses:Personal:Dave:Beverage:Beer    13.00 EUR 
  Assets:Cash
```

**Comment by glasserc** [comment]
The script currently supports `$13.00`, `€13.00`, and of course `13.00 USD`, but I didn't know `EUR 13.00` was valid Ledger syntax, so I never used it. I'd be happy to merge a PR that adds support for this.

**Comment by taprix** [comment]
@glasserc i think its a useful feature. I usually denote currencies in the format listed above and it works fine.
